import type { NextPage } from "next";
import { useState } from "react";
import Head from "next/head";
import Image from "next/image";
import axios from "axios";

const Home: NextPage = () => {
  const [mail, setMail] = useState("");

  function inputHandler(e: React.ChangeEvent<HTMLInputElement>) {
    setMail(e.target.value);
  }

  async function testApi(): Promise<void> {
    try {
      const ress = await axios.post(`api/sendmails`, { emailAddress: mail });
      console.log(ress, "ressss");
    } catch {}
  }

  return (
    <div>
      <Head>
        <title>Mail Sender Starter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Mail Sender Starter Pack</h1>
        <input type="email" onChange={inputHandler} />
        <button onClick={testApi}>Send Mail</button>
      </main>
    </div>
  );
};

export default Home;
